---
name: 'Build Example Art Moule'
on:
  workflow_dispatch:
  workflow_call:

permissions: {}
description: 'Build the example art module'
jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: ../../actions/setup-ls-primer.yml

      - name: Generate The Art Module
        run: pnpm nx g @logosphere/sdk:module --name art
        working-directory: ./ls-primer

      - name: Build The Art Module
        run: pnpm nx build muisc-gen
        working-directory: ./ls-primer

      - name: Generate The Art API
        run: pnpm nx g @logosphere/sdk:api --module art
        working-directory: ./ls-primer

      - name: Build The Art API
        run: pnpm nx build art-api
        working-directory: ./ls-primer

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./ls-primer/dist/apps/art/
          push: false
          tags: logosphere/art:latest
