export default {
  fieldName: 'getFeaturedListing',
  fieldNodes: [
    {
      kind: 'Field',
      name: {
        kind: 'Name',
        value: 'getFeaturedListing',
        loc: { start: 29, end: 47 },
      },
      arguments: [],
      directives: [],
      selectionSet: {
        kind: 'SelectionSet',
        selections: [
          {
            kind: 'Field',
            name: {
              kind: 'Name',
              value: 'identifier',
              loc: { start: 54, end: 64 },
            },
            arguments: [],
            directives: [],
            loc: { start: 54, end: 64 },
          },
          {
            kind: 'Field',
            name: {
              kind: 'Name',
              value: 'artwork',
              loc: { start: 70, end: 77 },
            },
            arguments: [],
            directives: [],
            selectionSet: {
              kind: 'SelectionSet',
              selections: [
                {
                  kind: 'Field',
                  name: {
                    kind: 'Name',
                    value: 'identifier',
                    loc: { start: 86, end: 96 },
                  },
                  arguments: [],
                  directives: [],
                  loc: { start: 86, end: 96 },
                },
                {
                  kind: 'Field',
                  name: {
                    kind: 'Name',
                    value: 'imageVariants',
                    loc: { start: 104, end: 117 },
                  },
                  arguments: [],
                  directives: [],
                  selectionSet: {
                    kind: 'SelectionSet',
                    selections: [
                      {
                        kind: 'Field',
                        name: {
                          kind: 'Name',
                          value: 'identifier',
                          loc: { start: 128, end: 138 },
                        },
                        arguments: [],
                        directives: [],
                        loc: { start: 128, end: 138 },
                      },
                      {
                        kind: 'Field',
                        name: {
                          kind: 'Name',
                          value: 'size',
                          loc: { start: 148, end: 152 },
                        },
                        arguments: [],
                        directives: [],
                        loc: { start: 148, end: 152 },
                      },
                    ],
                    loc: { start: 118, end: 160 },
                  },
                  loc: { start: 104, end: 160 },
                },
              ],
              loc: { start: 78, end: 167 },
            },
            loc: { start: 70, end: 167 },
          },
        ],
        loc: { start: 48, end: 171 },
      },
      loc: { start: 29, end: 171 },
    },
  ],
  returnType: 'Listing',
  parentType: 'Query',
  path: { key: 'getFeaturedListing', typename: 'Query' },
  schema: {
    __validationErrors: [],
    extensions: {},
    astNode: {
      kind: 'SchemaDefinition',
      operationTypes: [
        {
          kind: 'OperationTypeDefinition',
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'Query' },
          },
          operation: 'query',
        },
        {
          kind: 'OperationTypeDefinition',
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'Mutation' },
          },
          operation: 'mutation',
        },
      ],
    },
    extensionASTNodes: [],
    _queryType: 'Query',
    _mutationType: 'Mutation',
    _directives: ['@include', '@skip', '@deprecated', '@specifiedBy'],
    _typeMap: {
      AddressType: 'AddressType',
      Badge: 'Badge',
      SocialMediaType: 'SocialMediaType',
      ImageSize: 'ImageSize',
      SortDirection: 'SortDirection',
      ListingSortHeuristic: 'ListingSortHeuristic',
      UserSortHeuristic: 'UserSortHeuristic',
      BidResponseErrorType: 'BidResponseErrorType',
      WalletType: 'WalletType',
      VerificationResponse: 'VerificationResponse',
      Person: 'Person',
      ID: 'ID',
      String: 'String',
      Float: 'Float',
      Boolean: 'Boolean',
      User: 'User',
      Int: 'Int',
      Address: 'Address',
      Artwork: 'Artwork',
      Nft: 'Nft',
      Listing: 'Listing',
      BidEvent: 'BidEvent',
      SoldEvent: 'SoldEvent',
      SocialMedia: 'SocialMedia',
      ImageVariant: 'ImageVariant',
      ListingRequestFilters: 'ListingRequestFilters',
      ListingStatusFilter: 'ListingStatusFilter',
      MediaTypeFilter: 'MediaTypeFilter',
      UserRequestFilters: 'UserRequestFilters',
      IntRange: 'IntRange',
      PaginationInput: 'PaginationInput',
      BidResponseError: 'BidResponseError',
      SpotWallet: 'SpotWallet',
      Login: 'Login',
      NftProperty: 'NftProperty',
      PurchaseOrder: 'PurchaseOrder',
      PersonInput: 'PersonInput',
      AddressInput: 'AddressInput',
      UserSettings: 'UserSettings',
      ExternalWallet: 'ExternalWallet',
      UserResults: 'UserResults',
      NftCollection: 'NftCollection',
      ListingResults: 'ListingResults',
      ListingRequest: 'ListingRequest',
      UserRequest: 'UserRequest',
      BidResponse: 'BidResponse',
      S3SignedUrl: 'S3SignedUrl',
      ArtworkInput: 'ArtworkInput',
      CardanoExchangeRates: 'CardanoExchangeRates',
      UserInput: 'UserInput',
      CropInfo: 'CropInfo',
      PurchaseOrderSellerInput: 'PurchaseOrderSellerInput',
      UserSettingsInput: 'UserSettingsInput',
      SpotWalletEagerResults: 'SpotWalletEagerResults',
      ExternalWalletEagerResults: 'ExternalWalletEagerResults',
      WalletContents: 'WalletContents',
      Query: 'Query',
      Mutation: 'Mutation',
      __Schema: '__Schema',
      __Type: '__Type',
      __TypeKind: '__TypeKind',
      __Field: '__Field',
      __InputValue: '__InputValue',
      __EnumValue: '__EnumValue',
      __Directive: '__Directive',
      __DirectiveLocation: '__DirectiveLocation',
    },
    _subTypeMap: {},
    _implementationsMap: {},
  },
  fragments: {},
  operation: {
    kind: 'OperationDefinition',
    operation: 'query',
    name: {
      kind: 'Name',
      value: 'getFeaturedListing',
      loc: { start: 6, end: 24 },
    },
    variableDefinitions: [],
    directives: [],
    selectionSet: {
      kind: 'SelectionSet',
      selections: [
        {
          kind: 'Field',
          name: {
            kind: 'Name',
            value: 'getFeaturedListing',
            loc: { start: 29, end: 47 },
          },
          arguments: [],
          directives: [],
          selectionSet: {
            kind: 'SelectionSet',
            selections: [
              {
                kind: 'Field',
                name: {
                  kind: 'Name',
                  value: 'identifier',
                  loc: { start: 54, end: 64 },
                },
                arguments: [],
                directives: [],
                loc: { start: 54, end: 64 },
              },
              {
                kind: 'Field',
                name: {
                  kind: 'Name',
                  value: 'artwork',
                  loc: { start: 70, end: 77 },
                },
                arguments: [],
                directives: [],
                selectionSet: {
                  kind: 'SelectionSet',
                  selections: [
                    {
                      kind: 'Field',
                      name: {
                        kind: 'Name',
                        value: 'identifier',
                        loc: { start: 86, end: 96 },
                      },
                      arguments: [],
                      directives: [],
                      loc: { start: 86, end: 96 },
                    },
                    {
                      kind: 'Field',
                      name: {
                        kind: 'Name',
                        value: 'imageVariants',
                        loc: { start: 104, end: 117 },
                      },
                      arguments: [],
                      directives: [],
                      selectionSet: {
                        kind: 'SelectionSet',
                        selections: [
                          {
                            kind: 'Field',
                            name: {
                              kind: 'Name',
                              value: 'identifier',
                              loc: { start: 128, end: 138 },
                            },
                            arguments: [],
                            directives: [],
                            loc: { start: 128, end: 138 },
                          },
                          {
                            kind: 'Field',
                            name: {
                              kind: 'Name',
                              value: 'size',
                              loc: { start: 148, end: 152 },
                            },
                            arguments: [],
                            directives: [],
                            loc: { start: 148, end: 152 },
                          },
                        ],
                        loc: { start: 118, end: 160 },
                      },
                      loc: { start: 104, end: 160 },
                    },
                  ],
                  loc: { start: 78, end: 167 },
                },
                loc: { start: 70, end: 167 },
              },
            ],
            loc: { start: 48, end: 171 },
          },
          loc: { start: 29, end: 171 },
        },
      ],
      loc: { start: 25, end: 174 },
    },
    loc: { start: 0, end: 174 },
  },
  variableValues: {},
  cacheControl: { cacheHint: {} },
} as unknown;
