export const constants = {
  ARRAY: 'array',
  BOOLEAN: 'boolean',
  COMMENT: '$comment',
  DEFAULT: 'default',
  DEFS: '$defs',
  DESCRIPTION: 'description',
  ENUM: 'enum',
  EXAMPLES: 'examples',
  IS_ACTIVATED: 'isActivated',
  ITEMS: 'items',
  JSON_EXTENSION: '.json',
  LINKED_FILE_EXTENSION: '.hck.json',
  MAX_LENGTH: 'maxLength',
  MIN_LENGTH: 'minLength',
  NUMBER: 'number',
  OBJECT: 'object',
  PATTERN: 'pattern',
  PRIMARY_KEY: 'primaryKey',
  PROPERTIES: 'properties',
  READ_ONLY: 'readOnly',
  REF: '$ref',
  REQUIRED: 'required',
  STRING: 'string',
  TYPE: 'type',
  WRITE_ONLY: 'writeOnly',
};
