export const constants = {
  _ID: '_id',
  ID: 'id',
  PREDICATE: '_predicate',
  COLLECTION: '_collection',
  NAME: 'name',
  IDENTIFIER: 'identifier',
  CREATED_AT: 'createdAt',
  UPDATED_AT: 'updatedAt',
  OWNER: 'owner',
  USER: '_user',
  AUTH: '_auth',
  ROLE: '_role',
  RULE: '_rule',
  FUNCTION: '_fn',
};
