export default {
  fieldName: 'getFeaturedListings',
  fieldNodes: [
    {
      kind: 'Field',
      name: {
        kind: 'Name',
        value: 'getFeaturedListings',
        loc: { start: 30, end: 49 },
      },
      arguments: [],
      directives: [],
      selectionSet: {
        kind: 'SelectionSet',
        selections: [
          {
            kind: 'FragmentSpread',
            name: {
              kind: 'Name',
              value: 'MosaicTileListingInfo',
              loc: { start: 59, end: 80 },
            },
            directives: [],
            loc: { start: 56, end: 80 },
          },
          {
            kind: 'Field',
            name: {
              kind: 'Name',
              value: '__typename',
              loc: { start: 85, end: 95 },
            },
            arguments: [],
            directives: [],
            loc: { start: 85, end: 95 },
          },
        ],
        loc: { start: 50, end: 99 },
      },
      loc: { start: 30, end: 99 },
    },
  ],
  returnType: '[Listing]',
  parentType: 'Query',
  path: { key: 'getFeaturedListings', typename: 'Query' },
  schema: {
    __validationErrors: [],
    extensions: {},
    astNode: {
      kind: 'SchemaDefinition',
      operationTypes: [
        {
          kind: 'OperationTypeDefinition',
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'Query' },
          },
          operation: 'query',
        },
        {
          kind: 'OperationTypeDefinition',
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'Mutation' },
          },
          operation: 'mutation',
        },
      ],
    },
    extensionASTNodes: [],
    _queryType: 'Query',
    _mutationType: 'Mutation',
    _directives: ['@include', '@skip', '@deprecated', '@specifiedBy'],
    _typeMap: {
      AddressType: 'AddressType',
      Badge: 'Badge',
      SocialMediaType: 'SocialMediaType',
      ImageSize: 'ImageSize',
      SortDirection: 'SortDirection',
      ListingSortHeuristic: 'ListingSortHeuristic',
      UserSortHeuristic: 'UserSortHeuristic',
      BidResponseErrorType: 'BidResponseErrorType',
      WalletType: 'WalletType',
      VerificationResponse: 'VerificationResponse',
      Person: 'Person',
      ID: 'ID',
      String: 'String',
      Float: 'Float',
      Boolean: 'Boolean',
      User: 'User',
      Int: 'Int',
      Address: 'Address',
      Artwork: 'Artwork',
      Nft: 'Nft',
      Listing: 'Listing',
      BidEvent: 'BidEvent',
      SoldEvent: 'SoldEvent',
      SocialMedia: 'SocialMedia',
      ImageVariant: 'ImageVariant',
      ListingRequestFilters: 'ListingRequestFilters',
      ListingStatusFilter: 'ListingStatusFilter',
      MediaTypeFilter: 'MediaTypeFilter',
      UserRequestFilters: 'UserRequestFilters',
      IntRange: 'IntRange',
      PaginationInput: 'PaginationInput',
      BidResponseError: 'BidResponseError',
      SpotWallet: 'SpotWallet',
      Login: 'Login',
      NftProperty: 'NftProperty',
      PurchaseOrder: 'PurchaseOrder',
      PersonInput: 'PersonInput',
      AddressInput: 'AddressInput',
      UserSettings: 'UserSettings',
      ExternalWallet: 'ExternalWallet',
      UserResults: 'UserResults',
      NftCollection: 'NftCollection',
      ListingResults: 'ListingResults',
      ListingRequest: 'ListingRequest',
      UserRequest: 'UserRequest',
      BidResponse: 'BidResponse',
      S3SignedUrl: 'S3SignedUrl',
      ArtworkInput: 'ArtworkInput',
      CardanoExchangeRates: 'CardanoExchangeRates',
      UserInput: 'UserInput',
      CropInfo: 'CropInfo',
      PurchaseOrderSellerInput: 'PurchaseOrderSellerInput',
      UserSettingsInput: 'UserSettingsInput',
      SpotWalletEagerResults: 'SpotWalletEagerResults',
      ExternalWalletEagerResults: 'ExternalWalletEagerResults',
      WalletContents: 'WalletContents',
      Query: 'Query',
      Mutation: 'Mutation',
      __Schema: '__Schema',
      __Type: '__Type',
      __TypeKind: '__TypeKind',
      __Field: '__Field',
      __InputValue: '__InputValue',
      __EnumValue: '__EnumValue',
      __Directive: '__Directive',
      __DirectiveLocation: '__DirectiveLocation',
    },
    _subTypeMap: {},
    _implementationsMap: {},
  },
  fragments: {
    MosaicTileListingInfo: {
      kind: 'FragmentDefinition',
      name: {
        kind: 'Name',
        value: 'MosaicTileListingInfo',
        loc: { start: 112, end: 133 },
      },
      typeCondition: {
        kind: 'NamedType',
        name: {
          kind: 'Name',
          value: 'Listing',
          loc: { start: 137, end: 144 },
        },
        loc: { start: 137, end: 144 },
      },
      directives: [],
      selectionSet: {
        kind: 'SelectionSet',
        selections: [
          {
            kind: 'Field',
            name: {
              kind: 'Name',
              value: 'identifier',
              loc: { start: 149, end: 159 },
            },
            arguments: [],
            directives: [],
            loc: { start: 149, end: 159 },
          },
          {
            kind: 'Field',
            name: {
              kind: 'Name',
              value: 'currentPrice',
              loc: { start: 162, end: 174 },
            },
            arguments: [],
            directives: [],
            loc: { start: 162, end: 174 },
          },
          {
            kind: 'Field',
            name: {
              kind: 'Name',
              value: 'reservePrice',
              loc: { start: 177, end: 189 },
            },
            arguments: [],
            directives: [],
            loc: { start: 177, end: 189 },
          },
          {
            kind: 'Field',
            name: {
              kind: 'Name',
              value: 'buyNowPrice',
              loc: { start: 192, end: 203 },
            },
            arguments: [],
            directives: [],
            loc: { start: 192, end: 203 },
          },
          {
            kind: 'Field',
            name: {
              kind: 'Name',
              value: 'startDate',
              loc: { start: 206, end: 215 },
            },
            arguments: [],
            directives: [],
            loc: { start: 206, end: 215 },
          },
          {
            kind: 'Field',
            name: {
              kind: 'Name',
              value: 'endDate',
              loc: { start: 218, end: 225 },
            },
            arguments: [],
            directives: [],
            loc: { start: 218, end: 225 },
          },
          {
            kind: 'Field',
            name: {
              kind: 'Name',
              value: 'isLiked',
              loc: { start: 228, end: 235 },
            },
            arguments: [],
            directives: [],
            loc: { start: 228, end: 235 },
          },
          {
            kind: 'Field',
            name: {
              kind: 'Name',
              value: 'isWatched',
              loc: { start: 238, end: 247 },
            },
            arguments: [],
            directives: [],
            loc: { start: 238, end: 247 },
          },
          {
            kind: 'Field',
            name: {
              kind: 'Name',
              value: 'artwork',
              loc: { start: 250, end: 257 },
            },
            arguments: [],
            directives: [],
            selectionSet: {
              kind: 'SelectionSet',
              selections: [
                {
                  kind: 'Field',
                  name: {
                    kind: 'Name',
                    value: 'title',
                    loc: { start: 264, end: 269 },
                  },
                  arguments: [],
                  directives: [],
                  loc: { start: 264, end: 269 },
                },
                {
                  kind: 'Field',
                  name: {
                    kind: 'Name',
                    value: 'imageVariants',
                    loc: { start: 274, end: 287 },
                  },
                  arguments: [],
                  directives: [],
                  selectionSet: {
                    kind: 'SelectionSet',
                    selections: [
                      {
                        kind: 'Field',
                        name: {
                          kind: 'Name',
                          value: 'size',
                          loc: { start: 296, end: 300 },
                        },
                        arguments: [],
                        directives: [],
                        loc: { start: 296, end: 300 },
                      },
                      {
                        kind: 'Field',
                        name: {
                          kind: 'Name',
                          value: 'url',
                          loc: { start: 307, end: 310 },
                        },
                        arguments: [],
                        directives: [],
                        loc: { start: 307, end: 310 },
                      },
                      {
                        kind: 'Field',
                        name: {
                          kind: 'Name',
                          value: '__typename',
                          loc: { start: 317, end: 327 },
                        },
                        arguments: [],
                        directives: [],
                        loc: { start: 317, end: 327 },
                      },
                    ],
                    loc: { start: 288, end: 333 },
                  },
                  loc: { start: 274, end: 333 },
                },
                {
                  kind: 'Field',
                  name: {
                    kind: 'Name',
                    value: 'author',
                    loc: { start: 338, end: 344 },
                  },
                  arguments: [],
                  directives: [],
                  selectionSet: {
                    kind: 'SelectionSet',
                    selections: [
                      {
                        kind: 'Field',
                        name: {
                          kind: 'Name',
                          value: 'username',
                          loc: { start: 353, end: 361 },
                        },
                        arguments: [],
                        directives: [],
                        loc: { start: 353, end: 361 },
                      },
                      {
                        kind: 'Field',
                        name: {
                          kind: 'Name',
                          value: 'displayName',
                          loc: { start: 368, end: 379 },
                        },
                        arguments: [],
                        directives: [],
                        loc: { start: 368, end: 379 },
                      },
                      {
                        kind: 'Field',
                        name: {
                          kind: 'Name',
                          value: 'isFollowed',
                          loc: { start: 386, end: 396 },
                        },
                        arguments: [],
                        directives: [],
                        loc: { start: 386, end: 396 },
                      },
                      {
                        kind: 'Field',
                        name: {
                          kind: 'Name',
                          value: 'profileImageVariants',
                          loc: { start: 403, end: 423 },
                        },
                        arguments: [],
                        directives: [],
                        selectionSet: {
                          kind: 'SelectionSet',
                          selections: [
                            {
                              kind: 'Field',
                              name: {
                                kind: 'Name',
                                value: 'size',
                                loc: { start: 434, end: 438 },
                              },
                              arguments: [],
                              directives: [],
                              loc: { start: 434, end: 438 },
                            },
                            {
                              kind: 'Field',
                              name: {
                                kind: 'Name',
                                value: 'url',
                                loc: { start: 447, end: 450 },
                              },
                              arguments: [],
                              directives: [],
                              loc: { start: 447, end: 450 },
                            },
                            {
                              kind: 'Field',
                              name: {
                                kind: 'Name',
                                value: '__typename',
                                loc: { start: 459, end: 469 },
                              },
                              arguments: [],
                              directives: [],
                              loc: { start: 459, end: 469 },
                            },
                          ],
                          loc: { start: 424, end: 477 },
                        },
                        loc: { start: 403, end: 477 },
                      },
                      {
                        kind: 'Field',
                        name: {
                          kind: 'Name',
                          value: '__typename',
                          loc: { start: 484, end: 494 },
                        },
                        arguments: [],
                        directives: [],
                        loc: { start: 484, end: 494 },
                      },
                    ],
                    loc: { start: 345, end: 500 },
                  },
                  loc: { start: 338, end: 500 },
                },
                {
                  kind: 'Field',
                  name: {
                    kind: 'Name',
                    value: '__typename',
                    loc: { start: 505, end: 515 },
                  },
                  arguments: [],
                  directives: [],
                  loc: { start: 505, end: 515 },
                },
              ],
              loc: { start: 258, end: 519 },
            },
            loc: { start: 250, end: 519 },
          },
          {
            kind: 'Field',
            name: {
              kind: 'Name',
              value: 'listedBy',
              loc: { start: 522, end: 530 },
            },
            arguments: [],
            directives: [],
            selectionSet: {
              kind: 'SelectionSet',
              selections: [
                {
                  kind: 'Field',
                  name: {
                    kind: 'Name',
                    value: 'username',
                    loc: { start: 537, end: 545 },
                  },
                  arguments: [],
                  directives: [],
                  loc: { start: 537, end: 545 },
                },
                {
                  kind: 'Field',
                  name: {
                    kind: 'Name',
                    value: 'displayName',
                    loc: { start: 550, end: 561 },
                  },
                  arguments: [],
                  directives: [],
                  loc: { start: 550, end: 561 },
                },
                {
                  kind: 'Field',
                  name: {
                    kind: 'Name',
                    value: 'isFollowed',
                    loc: { start: 566, end: 576 },
                  },
                  arguments: [],
                  directives: [],
                  loc: { start: 566, end: 576 },
                },
                {
                  kind: 'Field',
                  name: {
                    kind: 'Name',
                    value: 'profileImageVariants',
                    loc: { start: 581, end: 601 },
                  },
                  arguments: [],
                  directives: [],
                  selectionSet: {
                    kind: 'SelectionSet',
                    selections: [
                      {
                        kind: 'Field',
                        name: {
                          kind: 'Name',
                          value: 'size',
                          loc: { start: 610, end: 614 },
                        },
                        arguments: [],
                        directives: [],
                        loc: { start: 610, end: 614 },
                      },
                      {
                        kind: 'Field',
                        name: {
                          kind: 'Name',
                          value: 'url',
                          loc: { start: 621, end: 624 },
                        },
                        arguments: [],
                        directives: [],
                        loc: { start: 621, end: 624 },
                      },
                      {
                        kind: 'Field',
                        name: {
                          kind: 'Name',
                          value: '__typename',
                          loc: { start: 631, end: 641 },
                        },
                        arguments: [],
                        directives: [],
                        loc: { start: 631, end: 641 },
                      },
                    ],
                    loc: { start: 602, end: 647 },
                  },
                  loc: { start: 581, end: 647 },
                },
                {
                  kind: 'Field',
                  name: {
                    kind: 'Name',
                    value: '__typename',
                    loc: { start: 652, end: 662 },
                  },
                  arguments: [],
                  directives: [],
                  loc: { start: 652, end: 662 },
                },
              ],
              loc: { start: 531, end: 666 },
            },
            loc: { start: 522, end: 666 },
          },
          {
            kind: 'Field',
            name: {
              kind: 'Name',
              value: '__typename',
              loc: { start: 669, end: 679 },
            },
            arguments: [],
            directives: [],
            loc: { start: 669, end: 679 },
          },
        ],
        loc: { start: 145, end: 681 },
      },
      loc: { start: 103, end: 681 },
    },
  },
  operation: {
    kind: 'OperationDefinition',
    operation: 'query',
    name: {
      kind: 'Name',
      value: 'getFeaturedListings',
      loc: { start: 6, end: 25 },
    },
    variableDefinitions: [],
    directives: [],
    selectionSet: {
      kind: 'SelectionSet',
      selections: [
        {
          kind: 'Field',
          name: {
            kind: 'Name',
            value: 'getFeaturedListings',
            loc: { start: 30, end: 49 },
          },
          arguments: [],
          directives: [],
          selectionSet: {
            kind: 'SelectionSet',
            selections: [
              {
                kind: 'FragmentSpread',
                name: {
                  kind: 'Name',
                  value: 'MosaicTileListingInfo',
                  loc: { start: 59, end: 80 },
                },
                directives: [],
                loc: { start: 56, end: 80 },
              },
              {
                kind: 'Field',
                name: {
                  kind: 'Name',
                  value: '__typename',
                  loc: { start: 85, end: 95 },
                },
                arguments: [],
                directives: [],
                loc: { start: 85, end: 95 },
              },
            ],
            loc: { start: 50, end: 99 },
          },
          loc: { start: 30, end: 99 },
        },
      ],
      loc: { start: 26, end: 101 },
    },
    loc: { start: 0, end: 101 },
  },
  variableValues: {},
  cacheControl: { cacheHint: {} },
} as unknown;
