---
name: 'Setup ls-primer Workspace'
description: 'Installs Node and sets up a clean ls-primer workspace'
runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v2
      with:
        version: 6.35.0

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: pnpm

    - name: Config PNPM
      run: pnpm config set auto-install-peers true

    - name: Install NX
      run: pnpm install -g nx@15.4.4

    - name: Create NX Workspace
      run: pnpm nx create-nx-workspace@15.4.4 --name ls-primer --pm pnpm --nxCloud false --preset empty

    - name: Install Latest SDK
      run: pnpm install @logosphere/sdk@latest
      working-directory: ./ls-primer

    - name: Install NX Node Plugins
      run: pnpm install @nrwl/node@15.4.4 @types/node @babel/core
      working-directory: ./ls-primer

    - name: Init NX Workspace
      run: pnpm nx g @logosphere/sdk:init
      working-directory: ./ls-primer
