---
name: 'Build The Logosphere Projects'
description: 'Builds all Logosphere Projects'
runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v2
      with:
        version: 6.35.0

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: pnpm

    - name: Config PNPM
      run: pnpm config set auto-install-peers true
      shell: bash

    - run: pnpm install
      shell: bash

    - run: pnpm build
      shell: bash
