query <%= camelize(name) %>FindAll{
  <%= camelize(name) %>FindAll{
    id,
    subjectId,
    <%_ definition.props.filter((p) => p.defType !== 'Entity' && p.defType !== 'EntityArray').map((p) => { -%>
    <%= camelize(p.name) %>,
    <%_ }) -%>
    createdAt,
    updatedAt
  }
}