export const constants = {
  _ID: '_id',
  AUTH: '_auth',
  COLLECTION: '_collection',
  CREATED_AT: 'createdAt',
  DOC: 'doc',
  FUNCTION: '_fn',
  ID: 'id',
  IDENTIFIER: 'identifier',
  NAME: 'name',
  OWNER: 'owner',
  PREDICATE: '_predicate',
  REF: 'ref',
  ROLE: '_role',
  RULE: '_rule',
  SPEC: 'spec',
  SPEC_DOC: 'specDoc',
  TIME: 'time',
  UPDATED_AT: 'updatedAt',
  USER: '_user',
  VERSION: 'version',
};

export const types = {
  STRING: 'string',
  BIGDEC: 'bigdec',
  BIGINT: 'bigint',
  BOOLEAN: 'boolean',
  BYTES: 'bytes',
  DOUBLE: 'double',
  FLOAT: 'float',
  INSTANT: 'instant',
  INT: 'int',
  JSON: 'json',
  LONG: 'long',
  URI: 'uri',
  UUID: 'uuid',
};
