export const constants = {
  _ID: '_id',
  AUTH: '_auth',
  BIGINT: 'bigint',
  COLLECTION: '_collection',
  CREATED_AT: 'createdAt',
  FUNCTION: '_fn',
  ID: 'id',
  IDENTIFIER: 'identifier',
  INSTANT: 'instant',
  NAME: 'name',
  OWNER: 'owner',
  PREDICATE: '_predicate',
  REF: 'ref',
  ROLE: '_role',
  RULE: '_rule',
  STRING: 'string',
  TIME: 'time',
  UPDATED_AT: 'updatedAt',
  USER: '_user',
};
