export const constants = {
  ARRAY: "array",
  BOOLEAN: "boolean",
  COMMENT: "$comment",
  DEFS: "$defs",
  DESCRIPTION: "description",
  ENUM: "enum",
  EXAMPLES: "examples",
  IS_ACTIVATED: "isActivated",
  ITEMS: "items",
  MAX_LENGTH: "maxLength",
  MIN_LENGTH: "minLength",
  NUMBER: "number",
  OBJECT: "object",
  PATTERN: "pattern",
  PRIMARY_KEY: "primaryKey",
  READ_ONLY: "readOnly",
  REF: "$ref",
  STRING: "string",
  TYPE: "type",
  WRITE_ONLY: "writeOnly",
};
