name: 'LS Primer Build and Deploy'
on:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build-and-publish-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/build-sdk
      # - run: pnpm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  build-and-deploy-demo:
    needs: build-and-publish-sdk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/setup-ls-primer
        with:
          NPM_CICD_TOKEN: ${{ secrets.NPM_CICD_TOKEN }}

      - uses: ./.github/actions/generate-music-app
      - uses: ./.github/actions/generate-art-app
      - uses: ./.github/actions/generate-helm-chart

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build The Art Docker Image
        run: pnpm nx docker art --build-args NPM_TOKEN=${{ secrets.NPM_CICD_TOKEN }}
        working-directory: /tmp/ls-primer
        env:
          NPM_TOKEN: ${{ secrets.NPM_CICD_TOKEN }}

      - name: Build The Music Docker Image
        run: pnpm nx docker music --build-args NPM_TOKEN=${{ secrets.NPM_CICD_TOKEN }}
        working-directory: /tmp/ls-primer
        env:
          NPM_TOKEN: ${{ secrets.NPM_CICD_TOKEN }}

      - name: Push The Docker Images
        run: >-
          docker tag logosphere/music:latest ikigaitech/ls-primer-music:latest &&
          docker tag logosphere/art:latest ikigaitech/ls-primer-art:latest &&
          docker push ikigaitech/ls-primer-music:latest &&
          docker push ikigaitech/ls-primer-art:latest

      - name: Package The Helm Chart
        run: >-
          tar -czf ls-primer.tar.gz /tmp/ls-primer/helm
