---
name: 'Build SDK'
on:
  workflow_dispatch:
  pull_request:
  push:
    - mm/cicd

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/build-sdk
