name: 'Build and Deploy Main'
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - mm/cicd

permissions:
  contents: read
  pull-requests: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: ls -la
#      - uses: .github/actions/builds/test/action.yml
#- uses: .github/actions/builds/art/action.yml
# - uses: .github/actions/builds/music
