name: 'SDK Build and Deploy'
on:
  workflow_dispatch:
  push:
    tags:
      - sdk-*

permissions:
  id-token: write
  contents: read
  pull-requests: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build-and-publish-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/build-logosphere

      - run: pnpm publish
        working-directory: dist/libs/sdk
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  call-publish-ls-primer:
    uses: ./.github/workflows/publish-ls-primer.yml
    needs: build-and-publish-sdk
