name: 'IPFS Build and Publish'
on:
  workflow_dispatch:
  push:
    tags:
      - ipfs-*

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: false

jobs:
  build-and-publish-ipfs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/build-logosphere

      - name: Authenticate with NPM
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_CICD_TOKEN }}" > .npmrc
        shell: bash

      - run: pnpm publish --no-git-checks dist/libs/ipfs
